Evidence_07/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Evidence_07.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Evidence_07.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        private readonly TraineeCourseDbContext db;
        public CourseController(TraineeCourseDbContext db) { this.db = db;}
        public IActionResult Index()
        {
            return View(db.Courses.ToList());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Course c)
        {
            Thread.Sleep(1000);
            if (ModelState.IsValid)
            {
                db.Courses.Add(c);
                db.SaveChanges();
                ViewBag.Success = true;
                ViewBag.Message = "Data saved successfully";
                return PartialView("_AjaxPartial");
            }

            ViewBag.Success = false;
            ViewBag.Message = "Failed to save data";
            return PartialView("_AjaxPartial");
        }
        public IActionResult Edit(int id)
        {
            return View(db.Courses.First(x => x.CourseId == id));
        }
        [HttpPost]
        public IActionResult Edit(Course ct)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ct).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ct);
        }
        public IActionResult Delete(int id)
        {
            return View(db.Courses.Include(x=>x.Trainees).First(x => x.CourseId == id));
        }
        [ActionName("Delete"), HttpPost]
        public IActionResult ConfirmDelete(int id)
        {
            Course c = new Course { CourseId = id };
            db.Entry(c).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Evidence_07/Controllers/TraineeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Evidence_07.Models;
using Evidence_07.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Evidence_07.Controllers
{
    [Authorize]
    public class TraineeController : Controller
    {
        private readonly TraineeCourseDbContext db;
        private readonly IHostingEnvironment env;
        public TraineeController(TraineeCourseDbContext db, IHostingEnvironment env) { this.db = db; this.env = env; }
        public IActionResult Index()
        {
            return View(db.Trainees.Include(x => x.Course).ToList());
        }
        public IActionResult Create()
        {
            ViewBag.CourseList = db.Courses.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult Create(TraineeViewModel t)
        {
            if (ModelState.IsValid)
            {
                Trainee e = new Trainee { TraineeName = t.TraineeName, Email = t.Email, TLocation = t.TLocation, Picture = "no-pic.png", CourseId=t.CourseId };
                if (t.Picture != null)
                {
                    var imagePath = env.WebRootPath + @"\uploads";

                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(t.Picture.FileName);
                    FileStream fs = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);
                    t.Picture.CopyTo(fs);
                    fs.Flush();
                    fs.Close();
                    e.Picture = fileName;
                }
                db.Trainees.Add(e);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(t);
        }
        public IActionResult Edit(int id)
        {
            var e = db.Trainees.First(x => x.TraineeId == id);
            ViewBag.picture = e.Picture;
            ViewBag.CourseList = db.Courses.ToList();
            return View(new TraineeViewModel
            {
                TraineeId = e.TraineeId,
                TraineeName = e.TraineeName,
                Email = e.Email,
                TLocation = e.TLocation,
                CourseId = e.CourseId
            });
        }
        [HttpPost]
        public IActionResult Edit(TraineeViewModel t)
        {
            if (ModelState.IsValid)
            {
                var tr = db.Trainees.First(x => x.TraineeId == t.TraineeId);
                tr.Email = t.Email;
                tr.TraineeName = t.TraineeName;
                tr.TLocation = t.TLocation;
                tr.CourseId = t.CourseId;
                if (t.Picture != null)
                {
                    var imagePath = env.WebRootPath + @"\uploads";
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(t.Picture.FileName);
                    FileStream fs = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);
                    t.Picture.CopyTo(fs);
                    fs.Flush();
                    fs.Close();
                    tr.Picture = fileName;
                }
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            ViewBag.CourseList = db.Courses.ToList();
            return View(t);
        }
        public IActionResult Delete(int id)
        {
            return View(db.Trainees.Include(x => x.Course).First(x => x.TraineeId == id));
        }
        [ActionName("Delete"), HttpPost]
        public IActionResult ConfirmDelete(int id)
        {
            Trainee t = new Trainee { TraineeId = id };
            db.Entry(t).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Evidence_07/Views/Shared/_AjaxPartial.cshtml
@if (ViewBag.Success == true)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Success!</strong> @ViewBag.Message
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
else
{
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Failed!</strong> @ViewBag.Message
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
}

Evidence_07/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <environment include="Development,Production">
        <link href="~/libs/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <script src="~/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">
        <style>
            body {
                padding-top: 70px;
            }

            .main {
                min-height: calc(100vh - 115px);
            }

            th, tr, td {
                text-align: center;
            }
            h1{
                text-align:center;
                color:darkblue;
            }
            
        </style>
    </environment>
    @RenderSection("styles", false)
</head>
<body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-md fixed-top shadow-sm">
        <div class="container-fluid">
            <span class="navbar-brand">Course & Trainee</span>
            <div class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Course" asp-action="Index">Courses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Trainee" asp-action="Index">Trainees</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    @if (User.Identity.IsAuthenticated)
                    {

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    }

                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid main">
        @RenderBody()
    </div>
    <footer class="container-fluid">
        <p>&copy; @DateTime.Now.Year - Course and Trainee</p>
    </footer>
    @RenderSection("scripts", false)
</body>
</html>